name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on a Linux machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Fetches the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Enables multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Fetches Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Fetches Docker Hub password from secrets

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  # Uses the current directory as the build context
          file: ./Dockerfile  # Specifies the Dockerfile to use
          push: true  # Enables pushing the image to Docker Hub
          tags: rahul5114/my-fastapi-app:latest  # Replace with your Docker Hub username
